name: gestion_tareas
description: Una aplicación Flutter para gestionar tareas

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
     sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  fl_chart: ^0.69.0
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
